//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBATools.Congresso.View.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        public long id { get; set; }
        public string nome { get; set; }
        public string end_rua { get; set; }
        public string end_numero { get; set; }
        public string end_complemento { get; set; }
        public string end_bairro { get; set; }
        public string end_cidade { get; set; }
        public string end_estado { get; set; }
        public string end_cep { get; set; }
        public long id_pais { get; set; }
        public string end_zipcode { get; set; }
        public string telefone { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string nome_cracha { get; set; }
        public string observacao { get; set; }
        public Nullable<System.DateTime> datahora_cadastro { get; set; }
        public Nullable<System.DateTime> datahora_alteracao { get; set; }
    }
}
