//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBATools.Congresso.View.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa_juridica : pessoa
    {
        public pessoa_juridica()
        {
            this.pessoa_fisica = new HashSet<pessoa_fisica>();
        }
    
        public long id_segmento { get; set; }
        public string cnpj { get; set; }
        public string insc_estadual { get; set; }
        public string insc_municipal { get; set; }
        public string codigo_produtor_rural { get; set; }
        public string doc_empresa_estrangeira { get; set; }
        public string nome_fantasia { get; set; }
        public string site { get; set; }
        public Nullable<System.DateTime> data_abertura { get; set; }
    
        public virtual ICollection<pessoa_fisica> pessoa_fisica { get; set; }
        public virtual segmento segmento { get; set; }
    }
}
