//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBATools.Congresso.View.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class segmento
    {
        public segmento()
        {
            this.pessoa_juridica = new HashSet<pessoa_juridica>();
        }
    
        public long id { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<pessoa_juridica> pessoa_juridica { get; set; }
    }
}
